//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DAL.Repository;

    public partial class SalesEntities : DbContext
    {
        public IGenericRepository<Contact> ContactRepository => new GenericRepository<Contact>(this);
        public IGenericRepository<Client> ClientRepository => new GenericRepository<Client>(this);
        public IGenericRepository<Manager> ManagerRepository => new GenericRepository<Manager>(this);
        public IGenericRepository<Product> ProductRepository => new GenericRepository<Product>(this);
        public IGenericRepository<Sale> SaleRepository => new GenericRepository<Sale>(this);

        public SalesEntities()
            : base("SalesEntities")
        {

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
    }
}
