//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Sale: BaseEntity
    {
        //public System.Guid Id { get; set; }
        [Required]
        public System.Guid ClientId { get; set; }
        [Required]
        public System.Guid ProductId { get; set; }
        [Required]
        public decimal Sum { get; set; }
        [Required]
        public System.DateTime Date { get; set; }
        [Required]
        public System.Guid CreatedByUserId { get; set; }
        [Required]
        public System.DateTime CreatedDateTime { get; set; }

        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Product Product { get; set; }
    }
}
